name = "kanban-board-public"
compatibility_date = "2026-07-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "kanban-board-db"
database_id = "32220ac9-e1f1-4297-bad8-438885777cb0"
migrations_dir = "migrations"
